//-------------------------------------------------------------------
// xpm_memory_tdpram_sim.v — Minimal behavioral model for simulation
//
// Replaces Vivado xpm_memory_tdpram for iverilog compatibility.
// Implements common_clock True Dual-Port RAM with read_first mode.
//
// Generated by unit-sim to work around iverilog's lack of
// concurrent assertion support in Vivado 2024.1 XPM library.
//-------------------------------------------------------------------

module xpm_memory_tdpram #(
    // Common module parameters
    parameter integer MEMORY_SIZE            = 2048,
    parameter          MEMORY_PRIMITIVE       = "auto",
    parameter          CLOCKING_MODE          = "common_clock",
    parameter          ECC_MODE               = "no_ecc",
    parameter          ECC_TYPE               = "NONE",
    parameter          ECC_BIT_RANGE          = "[7:0]",
    parameter          MEMORY_INIT_FILE       = "none",
    parameter          MEMORY_INIT_PARAM      = "",
    parameter integer  USE_MEM_INIT           = 1,
    parameter integer  USE_MEM_INIT_MMI       = 0,
    parameter          WAKEUP_TIME            = "disable_sleep",
    parameter integer  AUTO_SLEEP_TIME        = 0,
    parameter integer  MESSAGE_CONTROL        = 0,
    parameter integer  USE_EMBEDDED_CONSTRAINT = 0,
    parameter          MEMORY_OPTIMIZATION     = "true",
    parameter integer  CASCADE_HEIGHT          = 0,
    parameter          RAM_DECOMP              = "auto",
    parameter integer  SIM_ASSERT_CHK          = 0,
    parameter integer  WRITE_PROTECT           = 1,
    parameter integer  IGNORE_INIT_SYNTH       = 0,
    // Port A module parameters
    parameter integer  WRITE_DATA_WIDTH_A = 32,
    parameter integer  READ_DATA_WIDTH_A  = 32,
    parameter integer  BYTE_WRITE_WIDTH_A = 32,
    parameter integer  ADDR_WIDTH_A       = 10,
    parameter          READ_RESET_VALUE_A = "0",
    parameter integer  READ_LATENCY_A     = 2,
    parameter          WRITE_MODE_A       = "no_change",
    parameter          RST_MODE_A         = "SYNC",
    // Port B module parameters
    parameter integer  WRITE_DATA_WIDTH_B = 32,
    parameter integer  READ_DATA_WIDTH_B  = 32,
    parameter integer  BYTE_WRITE_WIDTH_B = 32,
    parameter integer  ADDR_WIDTH_B       = 10,
    parameter          READ_RESET_VALUE_B = "0",
    parameter integer  READ_LATENCY_B     = 2,
    parameter          WRITE_MODE_B       = "no_change",
    parameter          RST_MODE_B         = "SYNC"
) (
    input  wire                                  sleep,
    input  wire                                  clka,
    input  wire                                  rsta,
    input  wire                                  ena,
    input  wire                                  regcea,
    input  wire [WRITE_DATA_WIDTH_A/BYTE_WRITE_WIDTH_A-1:0] wea,
    input  wire [ADDR_WIDTH_A-1:0]               addra,
    input  wire [WRITE_DATA_WIDTH_A-1:0]         dina,
    input  wire                                  injectsbiterra,
    input  wire                                  injectdbiterra,
    output reg  [READ_DATA_WIDTH_A-1:0]          douta,
    output wire                                  sbiterra,
    output wire                                  dbiterra,
    input  wire                                  clkb,
    input  wire                                  rstb,
    input  wire                                  enb,
    input  wire                                  regceb,
    input  wire [WRITE_DATA_WIDTH_B/BYTE_WRITE_WIDTH_B-1:0] web,
    input  wire [ADDR_WIDTH_B-1:0]               addrb,
    input  wire [WRITE_DATA_WIDTH_B-1:0]         dinb,
    input  wire                                  injectsbiterrb,
    input  wire                                  injectdbiterrb,
    output reg  [READ_DATA_WIDTH_B-1:0]          doutb,
    output wire                                  sbiterrb,
    output wire                                  dbiterrb
);

  // ECC ports unused in simulation
  assign sbiterra  = 1'b0;
  assign dbiterra  = 1'b0;
  assign sbiterrb  = 1'b0;
  assign dbiterrb  = 1'b0;

  // Memory array: use max data width for simplicity
  localparam MAX_WIDTH = (WRITE_DATA_WIDTH_A > WRITE_DATA_WIDTH_B) ?
                          WRITE_DATA_WIDTH_A : WRITE_DATA_WIDTH_B;
  localparam DEPTH = MEMORY_SIZE / 8;  // bytes → addressable locations (byte-based)

  // Simple flat memory
  reg [MAX_WIDTH-1:0] mem [0:DEPTH-1];

  // Byte-enable widths (Vivado XPM standard):
  //   wea/web width = WRITE_DATA_WIDTH / BYTE_WRITE_WIDTH
  //   Each bit controls one byte of data
  localparam WEA_WIDTH = WRITE_DATA_WIDTH_A / BYTE_WRITE_WIDTH_A;
  localparam WEB_WIDTH = WRITE_DATA_WIDTH_B / BYTE_WRITE_WIDTH_B;

  // Port A
  generate
    if (READ_LATENCY_A >= 1) begin : gen_douta_reg
      always @(posedge clka) begin
        if (ena && regcea)
          douta <= mem[addra];
      end
    end else begin : gen_douta_comb
      always @(*) begin
        douta = mem[addra];
      end
    end
  endgenerate

  // Port A write with byte-enable support
  always @(posedge clka) begin
    if (ena) begin
      for (integer _a = 0; _a < WEA_WIDTH; _a = _a + 1) begin
        if (wea[_a])
          mem[addra][_a*8 +: 8] <= dina[_a*8 +: 8];
      end
    end
  end

  // Port B
  generate
    if (READ_LATENCY_B >= 1) begin : gen_doutb_reg
      always @(posedge clkb) begin
        if (enb && regceb)
          doutb <= mem[addrb];
      end
    end else begin : gen_doutb_comb
      always @(*) begin
        doutb = mem[addrb];
      end
    end
  endgenerate

  // Port B write with byte-enable support
  always @(posedge clkb) begin
    if (enb) begin
      for (integer _b = 0; _b < WEB_WIDTH; _b = _b + 1) begin
        if (web[_b])
          mem[addrb][_b*8 +: 8] <= dinb[_b*8 +: 8];
      end
    end
  end

endmodule
