# write_cpu_pkt.tcl — Write packets to cpu_channel CPU_WR FIFO (JTAG)
# Usage: source write_cpu_pkt.tcl
#        set pkt {0x9c 0x2d 0xcd ...}
#        write_one_pkt $pkt
#
# Registers:
#   0x10 cpu_wr_full       RO  1=full, cannot write
#   0x11 cpu_wr_wen        WC  write 1 then 0 to commit one byte
#   0x12 cpu_wr_waddr      RW  byte offset in pkt
#   0x13 cpu_wr_wdata      RW  byte data
#   0x14 cpu_wr_wpkt_len   RW  total pkt length
#   0x15 cpu_wr_wpkt_push  WC  write 1 then 0 to push into TX queue
#
# IMPORTANT: 0x11 and 0x15 must be "write 1 then immediately write 0"
#   to avoid data corruption and duplicate pushes.

# Clean leftover AXI transactions
catch {delete_hw_axi_txn read_txn}
catch {delete_hw_axi_txn write_txn}

proc write_one_pkt {byte_list} {
    catch {delete_hw_axi_txn read_txn}
    catch {delete_hw_axi_txn write_txn}

    set len [llength $byte_list]
    if {$len <= 0} {
        puts "ERROR: empty pkt"
        return 0
    }

    set full [expr {[jread 0x10]}]
    if {$full == 1} {
        puts "TX FIFO full, retry later"
        return 0
    }

    for {set i 0} {$i < $len} {incr i} {
        set b [expr {[lindex $byte_list $i] & 0xff}]
        jwrite 0x12 $i
        after 100
        jwrite 0x13 $b
        after 100
        jwrite 0x11 1
        after 100
        jwrite 0x11 0
        after 100
    }

    jwrite 0x14 $len
    after 200
    jwrite 0x15 1
    after 200
    jwrite 0x15 0

    puts "Written $len bytes and pushed to TX"
    return 1
}

proc write_pkt_hex {hex_list} {
    # hex_list example: {9c 2d cd ac 8f a4 ...}
    set bytes {}
    foreach h $hex_list { lappend bytes [expr "0x$h"] }
    write_one_pkt $bytes
}

# Write to TX, then read back from RX FIFO (loopback) and compare
proc write_and_verify {byte_list {timeout_ms 5000}} {
    set len [llength $byte_list]

    # Step 1: Write
    if {![write_one_pkt $byte_list]} { return 0 }

    # Step 2: Wait for RX
    puts "Waiting for loopback..."
    set waited 0
    while {[expr {[jread 0x00]}] == 1} {
        after 200
        incr waited 200
        if {$waited >= $timeout_ms} {
            puts "TIMEOUT: no loopback packet"
            return 0
        }
    }

    # Step 3: Pop and read
    jwrite 0x01 1; after 200; jwrite 0x01 0
    set rx_len [expr {[jread 0x02]}]
    puts "RX pkt_len: $rx_len (TX was $len)"

    jwrite 0x03 1
    set rx_bytes {}
    for {set i 0} {$i < $rx_len} {incr i} {
        jwrite 0x04 $i; after 200
        lappend rx_bytes [expr {[jread 0x05] & 0xff}]
    }
    jwrite 0x03 0

    # Step 4: Compare (skip FCS bytes 64-67, mac_tx recomputes CRC32)
    set mismatch 0
    set cmp_len [expr {$len - 4}]   ;# skip last 4 FCS bytes
    if {$cmp_len < 0} { set cmp_len 0 }
    for {set i 0} {$i < $cmp_len && $i < $rx_len} {incr i} {
        set tx_b [lindex $byte_list $i]
        set rx_b [lindex $rx_bytes $i]
        if {$tx_b != $rx_b} {
            puts "MISMATCH at byte $i: TX=0x[format %02x $tx_b] RX=0x[format %02x $rx_b]"
            incr mismatch
        }
    }
    if {$len != $rx_len} {
        puts "LENGTH mismatch: TX=$len RX=$rx_len"
    }
    if {$mismatch == 0} {
        puts "VERIFY PASS: first $cmp_len bytes match (FCS regenerated by mac_tx)"
        return 1
    } else {
        puts "VERIFY FAIL: $mismatch mismatches in first $cmp_len bytes"
        return 0
    }
}

puts "[info script] loaded: write_one_pkt / write_pkt_hex / write_and_verify"
